### PR TITLE
Don't use the npm bin command to resolve the bin path

### PR DESCRIPTION
**Pull request by tropictim**
This action is failing with the latest Ubuntu 22.04 image because npm updated to v9 which doesn't have the `bin` command. This change has fixed it for our repositories that are using the ubuntu image with npm v9

### CODE REVIEW

**Comment by junzhengca** [comment]
Having same issue with GitHub hosted runners.

Bumping this up so it gets reviewed :).

**Review by ovis96 — APPROVED** [review]
Looks good to me! 🚀

**Comment by Viicos** [comment]
Will fix https://github.com/creyD/prettier_action/issues/113

**Comment by andrashee** [comment]
Would be nice to merge this, to unblock PRs leveraging this action 👍

**Comment by creyD** [comment]
Thanks a lot for the quick PR! I will try this real quick on dev and then merge it to master, probably with a new release.

**Comment by dongcheolpark** [comment]
Hi guys, thanks for your great job! 
but I have some problem related with this issue..
image

here's my actions output. It doesn't seem like all of these issues have been resolved :(

Could this be only my problem?

**Comment by Viicos** [comment]
@dongcheolpark Use `v4.3` or the workaround described [here](https://github.com/creyD/prettier_action#problem-with-npm-v9-19022023)

**Comment by dongcheolpark** [comment]
> @dongcheolpark Use `v4.3` or the workaround described [here](https://github.com/creyD/prettier_action#problem-with-npm-v9-19022023)

I thought it was latest version.. thank you !!

**Pull request merged**
