### PR TITLE
Support not exiting the process in case of changes in dry mode

### LINKED ISSUE #80: [FEATURE] modify files without pushing
**What would you like to change about the program?**

I would like to be able to modify files without pushing

**Why do you think this is a cool idea?**
A clear and concise description of why your feature would improve the program.

for people who already have a commit and push process as part of their action, it is unnecessary to have to push twice.

### PR DESCRIPTION
**Pull request by chicco785**
Fixes #80
and allows commit and push of different steps to be combined in single commit and push.

### CODE REVIEW

**Comment by creyD** [comment]
Or if you have nothing against it I will merge it and adjust it then, just react to this message if you are alright with me changing the code.

**Comment by chicco785** [comment]
> Or if you have nothing against it I will merge it and adjust it then, just react to this message if you are alright with me changing the code.

I am on vacation, sorry for being slow, feel free to change, the important thing to me it’s the functionality ;)

**Comment by creyD** [comment]
Can't merge this at the moment, because it is not up to date with dev, would be great if you gave me the permissions (but please take your vacation first!).

**Comment by chicco785** [comment]
hi @creyD, 
I sent you an invitation to the repository

**Comment by chicco785** [comment]
> @chicco785 Thanks for your contribution, I will test this on DEV and later merge this to master

great! thanks a lot :)

**Pull request merged**
